cloudflare_api_key: "{{ lookup('community.general.onepassword', 'cloudflare api token', field='credential', vault='Lab') }}"
varsitygw_user: "{{ lookup('community.general.onepassword', 'varsitygw user', field='username', vault='Lab') }}"
varsitygw_password: "{{ lookup('community.general.onepassword', 'varsitygw user', field='password', vault='Lab') }}"