apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/refs/tags/v4.2.3/deployments/multus-daemonset-thick.yml

patchesStrategicMerge:
  - host-run-netns-patch.yaml