apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/kubernetes-sigs/node-feature-discovery/deployment/overlays/default?ref=v0.17.1

# We need to patch the namespace and add the label pod-security.kubernetes.io/enforce=privileged to the namespace to allow the privileged pods to run
patchesStrategicMerge:
- namespace.yaml
- configmap.yaml