apiVersion: v1
kind: Service
metadata:
  name: mini2
  namespace: external-dns
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mini2.fondevilla.io
spec:
  type: ExternalName
  externalName: 10.1.0.107
