apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki-minio-secret
  namespace: loki
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: accessKeyId
      remoteRef:
        key: minio-loki
        property: username
    - secretKey: secretAccessKey
      remoteRef:
        key: minio-loki
        property: password
