apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns

resources:
- manifests/externaldns.yaml
- manifests/namespace.yaml
- manifests/externalsecret.yaml
- manifests/mini.yaml
- manifests/servicemonitor.yaml