repositories:
  - name: charts-jetstack-io
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: charts-jetstack-io/cert-manager
    version: v1.19.4
    createNamespace: true
    values:
      installCRDs: true
      prometheus:
        servicemonitor:
          enabled: true
