apiVersion: v1
kind: PersistentVolume
metadata:
  name: zigbee2mqtt-net
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.1.0.4
    path: "/mnt/SSD/k8s_static_pv/z2m-data-volume-zigbee2mqtt-net-0-pvc-c5158e53-32fa-4951-b939-37074c22d4a0"
  storageClassName: manual