apiVersion: v1
data:
  config: |
    [global]
    public network = 10.1.0.0/24
    cluster network = 10.254.0.0/24
    public addr = ""
    cluster addr = ""
kind: ConfigMap
metadata:
  name: rook-config-override
  namespace: rook-ceph