---
- hosts: all
  gather_facts: no
  become: false
  tasks:
  - name: Test 1password
    ansible.builtin.debug:
      msg: "{{ cloudflare_api_key }}"
  - name: Test 1password varsitygw_user
    ansible.builtin.debug:
      msg: "{{ varsitygw_user }}"
  - name: Test 1password varsitygw_password
    ansible.builtin.debug:
      msg: "{{ varsitygw_password }}"
