repositories:
  - name: connect-helm-charts
    url: https://1password.github.io/connect-helm-charts

releases:
  - name: connect
    namespace: 1p
    chart: connect-helm-charts/connect
    version: 2.3.0
    createNamespace: true
    values:
