---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora-vm
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: fedora-vm
      annotations:
        kubevirt.io/allow-pod-bridge-network-live-migration: "true"
    spec:
      evictionStrategy: LiveMigrate
      domain:
        cpu:
          cores: 2
        resources:
          requests:
            memory: 16G
        devices:
          disks:
            - name: fedora-vm-pvc
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: podnet
            masquerade: {}
      networks:
        - name: podnet
          pod: {}
      volumes:
        - name: fedora-vm-pvc
          persistentVolumeClaim:
            claimName: fedora-vm-pvc
        - name: cloudinitdisk
          cloudInitNoCloud:
            networkData: |
              network:
                version: 1
                config:
                  - type: physical
                    name: eth0
                    subnets:
                      - type: dhcp
            userData: |-
              #cloud-config
              users:
                - name: cloud-user
                  ssh_authorized_keys:
                    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDmeYUhyDS0md1g62LRdaYPEYmikiJdA4X6+2Ci2XOmIzj4cVYzvf7MvITG6lV2G4PrSJK3n7uviSrrqUAZC6ug++oBs67mYmR+OBiV7otKTcqcJaaxoKrfMwhBovOMJ4eL7O4oVzp1FzL/MobA7rdf+b3NCY68LEwqveqBd1cSKLWgHI2s+1+dOcdvLmY/DA5EEm76js61FAbz+fiYSdhzY4HUunlHb9PyNW/TPi1fvpFTK8btjuh3Mz5fAkZSidrwmdq8Q4L2AuzSpYfGaEr9z5Ln1j/3JSCRYuJEGAdkGSatbA2VPKaoyu/EQOCdHnAB59Xgj9gNfLdxMW/ycNkleN6uLTeniFHTDcbWXT4uHG4YBr0UZi/ApEWlaAiloRrQVom5zKl2DowO8TpEtyY8rU+t+u62axuPwt1xaInvZHlrfeTixdEUWHJXHNxP/RmbghjdgtcidJuU1Bc8hSWDszmHAy0qFcd5nOHcwgvuEjxoJ/D9Fa7CqMU7Sx35+8E=
                  sudo: ['ALL=(ALL) NOPASSWD:ALL']
                  groups: sudo
                  shell: /bin/bash
              runcmd:
                - "sudo touch /root/installed"
                - "sudo dnf update"
                - "sudo dnf install httpd fastfetch -y"
                - "sudo systemctl daemon-reload"
                - "sudo systemctl enable httpd"
                - "sudo systemctl start --no-block httpd"

  dataVolumeTemplates:
  - metadata:
      name: fedora-vm-pvc
    spec:
      storage:
        resources:
          requests:
            storage: 50Gi
        accessModes:
          - ReadWriteMany
        storageClassName: "nfs-client"
      source:
        http:
          url: "https://dl.fedoraproject.org/pub/fedora/linux/releases/41/Cloud/x86_64/images/Fedora-Cloud-Base-Generic-41-1.4.x86_64.qcow2"